version: '3'

services:
  aerogate:
    build: ./aerogate
    ports:
      - "8080:8080"
    environment:
      ROUTE_LABEL: "prod-canary"  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend_network
    depends_on:
      - backend_service_prod_canary
      - backend_service_prod_main


  backend_service_prod_main:
    build: ./backend-service/prod-main
    labels:
      env: "prod-main"
    ports:
      - "8082-8083:80"
    deploy:
      replicas: 2
    networks:
      - backend_network

  backend_service_prod_canary:
    build: ./backend-service/prod-canary
    labels:
      env: "prod-canary"
    ports:
      - "8084-8085:80"
    deploy:
      replicas: 2
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge